config/routes.rb
Rails.application.routes.draw do
  resources :homes

  resources :pages

  resources :templates

  resources :texts

  root 'homes#index'

  devise_for :users
  resources :users do
    resources :images, :pages 
  end

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html %>
  </div>
  <div class="field">
    <%= f.label :css %><br>
    <%= f.text_area :css %>
  </div>
  <div class="field">
    <%= f.label :js %><br>
    <%= f.text_area :js %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :template_id %><br>
    <%= f.text_field :template_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pages</h1>

<table>
  <thead>
    <tr>
      <th>Html</th>
      <th>Css</th>
      <th>Js</th>
      <th>User</th>
      <th>Template</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.html %></td>
        <td><%= page.css %></td>
        <td><%= page.js %></td>
        <td><%= page.user %></td>
        <td><%= page.template %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Html:</strong>
  <%= @page.html %>
</p>

<p>
  <strong>Css:</strong>
  <%= @page.css %>
</p>

<p>
  <strong>Js:</strong>
  <%= @page.js %>
</p>

<p>
  <strong>User:</strong>
  <%= @page.user %>
</p>

<p>
  <strong>Template:</strong>
  <%= @page.template %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>