config/routes.rb
Rails.application.routes.draw do
  resources :homes

  resources :pages

  resources :templates

  resources :texts

  root 'homes#index'

  devise_for :users
  resources :users do
    resources :images, :pages 
  end

end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :user
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:user_id, :body)
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.user %></td>
        <td><%= text.body %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @text.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text.body %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>